# Generated by Django 3.0.6 on 2020-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.CharField(max_length=264, primary_key=True, serialize=False),
        ),
    ]
