# Generated by Django 3.0.6 on 2020-05-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_auto_20200531_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
