# Generated by Django 3.0.6 on 2020-05-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0005_auto_20200531_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endtime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='starttime',
            field=models.DateField(),
        ),
    ]
