# Generated by Django 3.0.6 on 2020-06-01 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0006_auto_20200531_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_periods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.Activity')),
            ],
        ),
    ]
